GPL/HostIsolation/TcFilter/TcFilter.bpf.c
README.md
non-GPL/Common/Common.c
non-GPL/Common/Common.h
non-GPL/HostIsolation/KprobeConnectHook/KprobeLoader.h
non-GPL/HostIsolationMapsUtil/UpdateIPsDemo.c
non-GPL/HostIsolationMapsUtil/UpdateMaps.c
non-GPL/HostIsolationMapsUtil/UpdateMaps.h
non-GPL/TcLoader/TcLoader.h
non-GPL/TcLoader/TcLoaderDemo.c

The allowed_subnets map will contain user-defined IPs and subnets.
The allowed_IPs map will now only be used by the KprobeConnectHook program
to dynamically add destination IPs that allowed processes want to connect to.
The TcFilter network filter checks both maps and allows the packet to
be transmitted if it finds a match in either map.

Add option to allow IP subnets

---

non-GPL/HostIsolationMapsUtil/UpdateMaps.c

AWS has an old kernel (4.14) where struct bpf_map did not have
the name field. Creating a map with a name caused an error.
Instead, create a map with no name. The maps are pinned to BPF FS
so bpftool should still show the names properly with 'map list'.

Fix map creation on AWS Linux

---

GPL/HostIsolation/TcFilter/BPFTcFilterTests.cpp
README.md

Since the maps are pinned to the filesystem
the tests might be flaky if the maps are not cleared at every iteration.
This test could be made more pure by non pinning the map. However we
really want to test that behavior as well because we rely on pinning and
non pinned maps could behave differently because they have a different
lifecycle.

tests: BPFTcFilterTests map unpin on teardown

---

.clang-format
GPL/EventProbe/EventProbe.bpf.c
GPL/EventProbe/FileEvents.h
GPL/EventProbe/Helpers.h
GPL/EventProbe/Maps.h
GPL/HostIsolation/KprobeConnectHook/Kerneldefs.h
GPL/HostIsolation/KprobeConnectHook/KprobeConnectHook.bpf.c
GPL/HostIsolation/TcFilter/Kerneldefs.h
GPL/HostIsolation/TcFilter/TcFilter.bpf.c
Jenkinsfile
non-GPL/Common/Common.c
non-GPL/Common/Common.h
non-GPL/EventsTrace/EventsTrace.c
non-GPL/HostIsolation/KprobeConnectHook/KprobeConnectHookDemo.c
non-GPL/HostIsolation/KprobeConnectHook/KprobeLoader.c
non-GPL/HostIsolation/KprobeConnectHook/KprobeLoader.h
non-GPL/HostIsolationMapsUtil/UpdateIPsDemo.c
non-GPL/HostIsolationMapsUtil/UpdateMaps.c
non-GPL/HostIsolationMapsUtil/UpdateMaps.h
non-GPL/HostIsolationMapsUtil/UpdatePidsDemo.c
non-GPL/LibEbpfEvents/LibEbpfEvents.c
non-GPL/LibEbpfEvents/LibEbpfEvents.h
non-GPL/TcLoader/TcLoader.c
non-GPL/TcLoader/TcLoader.h
non-GPL/TcLoader/TcLoaderDemo.c

This PR adds a `.clang-format`, formats the code, and updates the `Jenkinsfile` to error if code isn't formatted.
It's branched off #51 as it's not yet merged. Opening it up now to get reviews early.
Code can now be formatted as follows:
```bash
find GPL/ non-GPL/ -name "*.[c,h]" | xargs clang-format -i
```
Here's the `.clang-format` I added:
```yaml
BasedOnStyle: LLVM
IndentWidth: 4
BreakBeforeBraces: Linux
BinPackParameters: false
AlignConsecutiveAssignments: true
```
See all possible values that can go into a `.clang-format` [here](https://clang.llvm.org/docs/ClangFormatStyleOptions.html).
I'll give a small bit of rationale here for why I chose these values, but want to emphasize that I ultimately don't really care about the minutia of the code style, I just care that we have one and …

Format code and enforce code formatting in Jenkins

---

GPL/EventProbe/CMakeLists.txt
GPL/EventProbe/EbpfEventProto.h
GPL/EventProbe/EventProbe.bpf.c
GPL/EventProbe/Helpers.h
GPL/EventProbe/PathResolver.h
non-GPL/EventsTrace/EventsTrace.c

This PR adds Cmd's dentry resolver at `GPL/EventProbe/PathResolver.h` and uses it to grab the current working directory as a string on exec.
The dentry resolver is rather complicated, and as such is heavily commented. Comments in `ebpf_resolve_path_to_string` should fully explain how it works. Let me know if anything is unclear and I can elaborate on the details of how dentries/mounts/vfsmounts are linked together as necessary.

Add dentry resolver and pass up CWD on exec

---

non-GPL/EventsTrace/EventsTrace.c

This leads to segfault right after a setsid is printed.

fix(non-GPL/EventsTrace): break after printing setsid

---

cmake/modules/BPF.cmake
non-GPL/EventsTrace/EventsTrace.c
non-GPL/LibEbpfEvents/LibEbpfEvents.c
non-GPL/LibEbpfEvents/LibEbpfEvents.h

Fixes #49 
This pr implements event filtering for `LibEbpfEvents` and adds the relevant CLI argument sto `EventsTrace` to do the filtering in the program itself.
The two things are done in two separate commits to make reviewing easier.

Implement event filtering

---

GPL/EventProbe/FileEventsHelpers.h
GPL/EventProbe/Maps.h
GPL/EventProbe/PathResolver.h

Closes https://github.com/elastic/ebpf/issues/68
@rhysre I've changed the scratch map in PathResolver to a percpu-array since the execution is always in the context of a single ebpf program. Let me know if that's ok for you

Use BTF-defined map defs and change PathResolver scratch map to a percpu-array

---

GPL/EventProbe/EbpfEventProto.h
GPL/EventProbe/File/Probe.bpf.c
GPL/EventProbe/Network/Network.h
GPL/EventProbe/Network/Probe.bpf.c
GPL/EventProbe/Process/Probe.bpf.c
non-GPL/EventsTrace/EventsTrace.c

To do / discuss:
```
{"family":"AF_INET","source_address":"10.0.2.100","source_port":42270,"destination_address":"157.90.119.155","destination_port":443,"network_namespace":4026534259}
{"family":"AF_INET","source_address":"192.168.1.3","source_port":43526,"destination_address":"157.90.119.155","destination_port":443,"network_namespace":4026532008}
``` 
Why it happened: we debugged this with @fntlnz and discovered that the second event was being triggered by [slirp4netns](https://github.com/rootless-containers/slirp4netns) because I was using Podman in rootless mode. This doesn't happen using Docker
Closes https://github.com/elastic/ebpf/issues/61
Closes https://github.com/elastic/ebpf/issues/62
Closes https://github.com/elastic/ebpf/issues/63

Network events

---

cmake/modules/BPF.cmake

Set USE_BUILTIN_VMLINUX to default to True.
On systems with kernels that don't provide BTF info, the build will fail
when the builtin vmlinux is not used. So defaulting to use builtin
vmlinux is the safer/more compatible build option.

Default to using builtin vmlinux

---

CMakeLists.txt
GPL/EventProbe/File/Probe.bpf.c
GPL/EventProbe/Helpers.h
GPL/EventProbe/Network/Probe.bpf.c
GPL/EventProbe/Process/Probe.bpf.c
GPL/EventProbe/State.h
non-GPL/EventsTrace/EventsTrace.c
non-GPL/LibEbpfEvents/LibEbpfEvents.c
non-GPL/LibEbpfEvents/LibEbpfEvents.h
non-GPL/LibEbpfEventsTestLoader/CMakeLists.txt
non-GPL/LibEbpfEventsTestLoader/LibEbpfEventsTestLoader.c

1. finally use `features` to make decisions during probe load-link
2. add a small utility binary `LibEbpfEventsTestLoader` which tries to load the probe with every combination of features for a fast feedback during development
3. add the possibility to specify features in `EventsTrace`
4. adds aarch64 support

EventProbe: aarch64 support

---

GPL/EventProbe/EbpfEventProto.h
GPL/EventProbe/File/Probe.bpf.c
GPL/EventProbe/Network/Network.h
GPL/EventProbe/State.h
non-GPL/EventsTrace/EventsTrace.c

I investigated a bit and seems that the issue is caused by how [overlayfs](https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt) work. 
I reproduced with
```
~ /tmp sudo mount -t overlay overlay -olowerdir=/tmp/lower,upperdir=/tmp/upper,workdir=/tmp/work /tmp/merged
~ /tmp/merged touch test
~ /tmp/merged rm test
{"event_type":"FILE_DELETE",..,"path":"./test","mount_namespace":4026531840,"comm":"rm"}
{"event_type":"FILE_DELETE",..,"path":"./test","mount_namespace":4026531840,"comm":"rm"}
```
```
~ lsns -t mnt
NS TYPE NPROCS   PID USER COMMAND
4026531840 mnt     121 24401 matt /usr/lib/systemd/systemd --user
4026533394 mnt       1 53972 matt podman
```
The only solution I could find is to explicitly delete the state so the event relative to the second `vfs_*` call gets …

EventProbe: delete state right after sending the event

---

GPL/EventProbe/File/Probe.bpf.c
GPL/EventProbe/State.h
non-GPL/LibEbpfEvents/LibEbpfEvents.c

Keep track of state changes for file delete and file rename events. This prevents function calls to intermediate functions from modifying the state in the same execution context.
Tested locally via EventsTrace.
Before:
```
podman run -it --rm ubuntu
root@cf180b13a634:/# touch ciao
root@cf180b13a634:/# rm ciao
./non-GPL/EventsTrace/EventsTrace --file-delete
{"event_type":"FILE_DELETE","pids":...,"path":"./ciao","mount_namespace":4026533390,"comm":"rm"}
```
After:
```
podman run -it --rm ubuntu
root@cf180b13a634:/# touch ciao
root@cf180b13a634:/# rm ciao
./non-GPL/EventsTrace/EventsTrace --file-delete
{"event_type":"FILE_DELETE","pids":...,"path":"/ciao","mount_namespace":4026533390,"comm":"rm"}
```
The same applies to rename events.
Co-Authored-By: Rhys Rustad-Elliott …

EventProbe: keep track of state changes for file events

---

CMakeLists.txt
GPL/Events/CMakeLists.txt
GPL/Events/PathResolver.h
GPL/HostIsolation/CMakeLists.txt
GPL/HostIsolation/KprobeConnectHook/CMakeLists.txt
GPL/HostIsolation/TcFilter/CMakeLists.txt
Makefile
cmake/modules/BPF.cmake
cmake/modules/arch.cmake
cmake/modules/libbpf.cmake
cmake/modules/libelf.cmake
non-GPL/Events/EventsTrace/CMakeLists.txt
non-GPL/Events/Lib/CMakeLists.txt
non-GPL/HostIsolation/Demos/CMakeLists.txt
non-GPL/HostIsolation/Lib/CMakeLists.txt

This commit cleans up the cmake in this repository, removing a lot of
vestigial stuff from when this repo was just host isolation and putting
it in a state where it can be more cleanly built with endpoint.
Changes:
- Remove all the TARGET_* variables in the top level CMakelists.txt,
push all that logic down to lower subdirectories
- Create a "libbpf" and "libelf" library target, instead of linking
against `${LIBBPF_LIB}` and `${LIBELF_LIB}` and then manually including
the required includes. This puts logic pertaining to where to find
libbpf includes in cmake/libbpf.cmake instead of GPL/non-GPL, which
means that we don't have to manually add the libbpf include
directories and link libraries to every target that links against it.
- Remove a bunch of unneeded comments, message(...) …

Cleanup CMake usage

---

GPL/Events/Process/Probe.bpf.c
GPL/HostIsolation/TcFilter/CMakeLists.txt
Makefile
cmake/modules/libbpf.cmake
non-GPL/Events/EventsTrace/CMakeLists.txt
non-GPL/Events/Lib/EbpfEvents.c
non-GPL/HostIsolation/Demos/CMakeLists.txt
testing/testrunner/main.go

This PR fixes two endpoint build issues.
- `libbpf` did `target_link_libraries(libbpf ... -lz)`, which resulted in the library _dynamically_ linking to libz, which we can't have with endpoint. Remove the `-lz` target link library from libbpf and just manually add it in all test/utility executables that need it. We'll statically link it in the endpoint build. It should be replaced with the vendored libz when that's added
- The `tty_write` probe is broken on kernels that have been built with pahole < 1.22. The reason for this is involved, see spoiler below if you're interested. For the time being, ifdef it out to get the endpoint build working (we don't need tty_write data right now). Once we have a working endpoint build, I'll get to fixing it.
<details>
<summary>tty_write problem …

Fix endpoint build issues

---

GPL/Events/Process/Probe.bpf.c
Makefile

On kernels with the PREEMPT_RT patch, the trace_entry struct, which
is the first member of trace_event_raw_sys_exit struct (the ctx for the
setsid exit probe) has two extra members.
We access the ret field of ctx via ctx->ret, which compiles to a
hardcoded offset. We should be using BPF_CORE_READ such that a
relocation is emitted so the correct offset is accessed on rt kernels.

Fix probes not loading on kernels with the PREEMPT_RT patch

---

EXCLUSIONS.md

These kernels modularize the serial driver. This does not mesh with our test framework.

Add Oracle kernels to EXCLUSIONS.md

---

GPL/Events/EbpfEventProto.h
GPL/Events/Process/Probe.bpf.c
non-GPL/Events/EventsTrace/EventsTrace.c
non-GPL/Events/Lib/EbpfEvents.c
testing/run_tests.sh
testing/scripts/build_mainline_kernels.sh
testing/testrunner/main.go

Use a different function to obtain signature indexes as `tty_write` BTF info are missing on ARM systems. Read more: https://github.com/elastic/ebpf/pull/116#issue-1327583872
Co-Authored-By: Rhys Rustad-Elliott <rhys.rustad-elliott@elastic.co>

EventProbe: use redirected_tty_write BTF info instead of tty_write

---

.gitignore
cmake/modules/BPF.cmake

Not sure why but `add_custom_target` always rebuilds non-GPL/Events/Lib/CMakeFiles/EbpfEvents.dir/EbpfEvents.c.o
Using a combo of `add_custom_command` and `add_custom_target` prevents the object file from being rebuilt when not necessary.

Prefer add_custom_command to add_custom_target

---

GPL/Events/CMakeLists.txt
GPL/HostIsolation/KprobeConnectHook/CMakeLists.txt
GPL/HostIsolation/TcFilter/CMakeLists.txt
cmake/modules/BPF.cmake

Previously, EbpfEvents.c.o and libEbpfEvents.a would not be rebuilt if probe source files were updated, likewise for host isolation libs. This PR make cmake aware of those sources and ensures a rebuild happens on changes to those files.

Track the probe source files

---

testing/test_bins/tcpv6_connect.c
testing/testrunner/main.go
testing/testrunner/tests.go

These tests are completely analogous to the IPv4 tests added in #142 except for the fact that they're IPv6.

Add IPv6 multi-kernel network tests

---

EXCLUSIONS.md
GPL/Events/Process/Probe.bpf.c
README.md
non-GPL/Events/EventsTrace/EventsTrace.c
non-GPL/Events/Lib/EbpfEvents.c
non-GPL/Events/Lib/EbpfEvents.h
testing/testrunner/eventstrace.go

Since the very beginning, the logic to detect if we support BPF (and all required BPF features) has been done in endpoint instead of in the ebpf events library. This is wonky. Logically, this logic belongs here, the library should be performing all necessary checks and returning `-ENOTSUP` if it can't load the probes. Library users shouldn't have to divine the specific system characteristics needed for the library to successfully run themselves.
This PR moves all the support-detection logic from endpoint to this repository, clarifies the minimum supported Linux version as 5.10.16 (not 5.10.10) and simplifies related feature detection logic. See commit messages for detailed explanations.

Move BPF support-detection logic from endpoint to this repository

---

Makefile
docker/Dockerfile.builder

Dockerfile update to workaround aarch64 install failures for clang-format 15.0.4 released on nov4

[8.6] Fix clang-format breakage due to llvm 15 release (#163)

---

non-GPL/Events/EventsTrace/EventsTrace.c
non-GPL/Events/Lib/EbpfEvents.c
non-GPL/Events/Lib/EbpfEvents.h

This PR exposes a *__consume function
And renames *__next to *__poll
The main idea here is to allow users to avoid a second polling call, if polling is done outside this library.

Align with libbpf function names

---

GPL/Events/Process/Probe.bpf.c

Fix probe load with veristat:
```
returning from callee:
frame2: R0_w=scalar() R1_w=scalar(umax=16777215,var_off=(0x0; 0xffffff)) R2_w=scalar(umax=65535,var_off=(0x0; 0xffff)) R3_w=scalar(umax=65535,var_off=(0x0; 0xffff)) R4_w=scalar(umax=16777215,var_off=(0x0; 0xffffff)) R5_w=scalar(umax=65535,var_off=(0x0; 0xffff)) R6=fp-56 R7_w=scalar(id=18) R8=scalar(id=15) R10=fp0 fp-8_w=mmmmmmmm fp-16= fp-24_w=mmmmmmmm fp-32_w=mmmmmmmm fp-40_w=mmmmmmmm fp-48_w=mmmmmmmm fp-56_w=mmmmmmmm fp-64=????mmmm fp-72=mmmmmmmm fp-80=mmmmmmmm fp-88=mmmmmmmm fp-96=mmmmmmmm fp-104=mmmmmmmm
to caller at 91:
frame1: R0_w=scalar() R6=scalar(id=1) R7=scalar(id=14) R8=scalar(id=14) R9=1 R10=fp0 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=mmmmmmmm fp-32=mmmmmmmm fp-40=mmmmmmmm fp-48=mmmmmmmm fp-56=mmmmmmmm fp-64=mm??????
; if …
```

fix: failed byte off relocation for iov_iter.iov

---

GPL/Events/File/Probe.bpf.c
GPL/Events/Helpers.h
GPL/Events/State.h

When compiling `EventProbe` with clang-16 and loading it both with a Go loader and veristat, there's a verifier error:
```
libbpf: prog 'kprobe__vfs_unlink': BPF program load failed: Permission denied
libbpf: prog 'kprobe__vfs_unlink': failed to load: -13
libbpf: failed to load object 'bpf_bpfel_x86.o'
PROCESSING bpf_bpfel_x86.o/kprobe__vfs_unlink, DURATION US: 46, VERDICT: failure, VERIFIER LOG:
0: R1=ctx(off=0,imm=0) R10=fp0
; int err = FUNC_ARG_READ_PTREGS(de, vfs_unlink, dentry);
0: (18) r2 = 0xffff9bf5409ba004       ; R2_w=map_value(off=4,ks=4,vs=32,imm=0)
2: (61) r2 = *(u32 *)(r2 +0)          ; R2_w=0
3: (65) if r2 s> 0x1 goto pc+5        ; R2_w=0
4: (15) if r2 == 0x0 goto pc+10       ; R2_w=0
15: (b7) r2 = 112                     ; R2_w=112
16: (05) goto pc+3
20: (0f) r1 += r2 …
```

fix: dereference of modified ctx ptr with clang16

---

GPL/Events/EbpfEventProto.h
GPL/Events/File/Probe.bpf.c
GPL/Events/State.h
non-GPL/Events/EventsTrace/EventsTrace.c
non-GPL/Events/Lib/EbpfEvents.c
testing/test_bins/create_rename_delete_file.c
testing/testrunner/tests.go
testing/testrunner/utils.go

Veristat output:
```Processing 'EventProbe.bpf.o'...
File              Program                              Verdict  Duration (us)  Insns  States  Peak states
----------------  -----------------------------------  -------  -------------  -----  ------  -----------
EventProbe.bpf.o  fentry__commit_creds                 success            331    740      35           35
EventProbe.bpf.o  fentry__do_renameat2                 success             71     68       4            4
EventProbe.bpf.o  fentry__do_unlinkat                  success             55     50       2            2
EventProbe.bpf.o  fentry__mnt_want_write               success             60     37       3            3
EventProbe.bpf.o  fentry__taskstats_exit               success          20725  26453    1397           78 …
```

EventProbe: add file modification events

---

LICENSE.txt

As discussed by the Open Source Working Group, we intend this to be an "or", under the terms by the user.

Clarify that license terms are "or" not "and"

---

GPL/Events/EbpfEventProto.h
GPL/Events/File/Probe.bpf.c
non-GPL/Events/EventsTrace/EventsTrace.c

Tested manually
```
➜  ebpf git:(matt/file-creds) ✗ sudo ./artifacts-x86_64/non-GPL/Events/EventsTrace/EventsTrace -i --file-create
{"probes_initialized": true, "features": {"bpf_tramp": true}}
{"event_type":"FILE_CREATE","pids":{"tid":2639926,"tgid":2318768,"ppid":3224,"pgid":3224,"sid":3224,"start_time_ns":538596506094300},"creds":{"ruid":1000,"rgid":1000,"euid":1000,"egid":1000,"suid":1000,"sgid":1000,"cap_permitted": "0","cap_effective": "0"},"mount_namespace":4026531841,"comm":"BgIOThr~ol #233","file_info":{"type":"FILE","inode":56644481,"mode":100644,"size":0,"uid":1000,"gid":1000,"atime":1709316588121009722,"mtime":1709316588121009722,"ctime":1709316588121009722},"path":"/home/matt/.mozilla/firefox/lpqgi4lp.default-release/sessionstore-backups/recovery.jsonlz4.tmp","symlink_target_p …
```

file events: add creds info

---

non-GPL/Events/Lib/EbpfEvents.h

This makes the library compile with -Werror=strict-prototypes, symbols that take no arguments should declare them as void.

Fix invalid prototype (-Werror=strict-prototypes)

---

GPL/Events/EbpfEventProto.h

Otherwise running two FOREACHes in the same scope won't work as it tries to redefine the variable.

Define the iterator in the for scope

---

non-GPL/CMakeLists.txt
non-GPL/Events/EventsTrace/EventsTrace.c
non-GPL/Events/Lib/EbpfEvents.c
non-GPL/HostIsolation/Lib/Common.h
non-GPL/HostIsolation/Lib/KprobeLoader.c
non-GPL/HostIsolation/Lib/TcLoader.c
non-GPL/HostIsolation/Lib/UpdateMaps.c
non-GPL/HostIsolation/Lib/UpdateMaps.h

- Get_auxiliary_vector_base() leaks an fd as it never calls fclose()
- Fix a bunch of signed vs unsigned
- Use ssize_t and size_t where deemed
- Avoid void * arithmetic, while gcc and clang capitulated and implicit cast to char *, it's still undef behavior by the standard.
- Declare some remaining prototypes as void
- Add the following to CFLAGS only on our code (non-GPL/*)
- Consistently use NLMSG_TAIL, I think there is one remaining bug where one caller doesn't align the length up, but I'd address that in a separate PR, I don't this diff to be too invasive.
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wextra")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Werror")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wchar-subscripts")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wcomment")
set(CMAKE_C_FLAGS …
```

Plug a fd leak, add a bunch of warnings and fix minor things

---

GPL/Events/EbpfEventProto.h
GPL/Events/Helpers.h
GPL/Events/Process/Probe.bpf.c
non-GPL/Events/EventsTrace/EventsTrace.c

This is needed by quark and it makes sense at any rate since we don't track COMM changes explicitly (setproctitle and friends).

Add COMM to process events fork/exec/exit

---

GPL/Events/EbpfEventProto.h
GPL/Events/Process/Probe.bpf.c
non-GPL/Events/EventsTrace/EventsTrace.c

Compiles and runs, needs proper testing and cleanup.

Condense is_foo from exec into flags.

---

GPL/Events/EbpfEventProto.h
GPL/Events/Process/Probe.bpf.c
non-GPL/Events/EventsTrace/EventsTrace.c

This unifies what fork+exec+exit outputs once and for all. cwd cannot be gathered on exit as it's already gone by the time we try to fetch it.

Add cwd to fork and ctty to exit.

---

GPL/Events/EbpfEventProto.h
GPL/Events/File/Probe.bpf.c
GPL/Events/Helpers.h
GPL/Events/Process/Probe.bpf.c
GPL/Events/Varlen.h
non-GPL/Events/EventsTrace/EventsTrace.c
non-GPL/Events/Lib/EbpfEvents.c
non-GPL/Events/Lib/EbpfEvents.h

This adds a new structure `ebpf_event_stats` where we accumulate stats, right now it only counts lost events vs non-lost events, but we can grow this in the future, like adding per type events if it's interesting enough.
The print in EventsTrace is quite primitive as I believe this will only be used for debugging there, so heh.
Choosing a name for `ebpf_ringbuf_write` was a bit tricky, I wanted to keep the same parameters but it had to be "different enough" that we could spot it with a naked eye.
While here, adjust the enum of ebpf events to not skip that precious first bit.

Basic ringbuf event statistics

---

GPL/Events/Helpers.h
GPL/Events/Network/Probe.bpf.c
non-GPL/Events/Lib/EbpfEvents.c

closes https://github.com/elastic/ebpf/issues/200
This changes the `inet_csk_accept` fexit probe to use `FUNC_RET_READ` instead of passing args to the method; this means we don't have to deal with the function arguments changing, like with the 6.10 kernel.
Tested on Fedora with 6.10.3, but we seem to be missing the addr fields. Not sure if this is a quirk of using the fexit probe, or if there's a bug here and the `inet_csk_accept` method no longer works the way we assume.
```
sudo ./EventsTrace --net-conn-accept -i                                                                                                                                                   
{"probes_initialized": true, "features": {"bpf_tramp": true}}
{"event_type":"NETWORK_CONNECTION_ACCEPTED","pids":{"tid":4184470,"tgi …
```

Use `FUNC_RET_READ` for `inet_csk_accept`

---

GPL/Events/Process/Probe.bpf.c

See https://github.com/inspektor-gadget/inspektor-gadget/issues/2444#issuecomment-1966440483
and see https://github.com/inspektor-gadget/inspektor-gadget/pull/2546
and see https://lore.kernel.org/lkml/20231005123413.GA488417@alecto.usersys.redhat.com/t/#u
This change fixes test failures in RHEL 9.

Use the proper struct for syscall tracepoint probes

---

GPL/Events/EbpfEventProto.h
GPL/Events/File/Probe.bpf.c
GPL/Events/Helpers.h
GPL/Events/Network/Probe.bpf.c
GPL/Events/Process/Probe.bpf.c

`bpf_ktime_get_ns` does not include suspension time, but we would like `hdr.ts` to represent real world time. Switching the helper function achieves that. The helper was introduced in 5.8 which is earlier than our current support range, 5.10
Update:
Add a new member variable instead and leave `hdr.ts` alone.

Use bpf_ktime_get_boot_ns instead

---

GPL/Events/EbpfEventProto.h
GPL/Events/File/Probe.bpf.c
GPL/Events/Helpers.h
GPL/Events/Process/Probe.bpf.c
non-GPL/Events/EventsTrace/EventsTrace.c
testing/scripts/gen_initramfs.sh
testing/testrunner/ebpf_test.go
testing/testrunner/utils.go

This diff adds the inode number of each namespace the process belongs to, to process events. Two namespaces were excluded: pid_for_children and time_for_children, see namespaces(7).
The pid namespace is a bit special as it's not in nsproxy, the user facing pid level is the last/deepest.
There was an inclusion of mnt ns, that is not used by beats or endpoint, I kept it but made it fetch from the new "path".
While here, add support for changing the compiler in gen_initramfs.sh by setting CC. While Fedora includes a ${arch}-linux-gnu-gcc, it doesn't include matching headers, so I can't really compile the tests locally.

Include namespace inode numbers on process events

---

GPL/Events/Process/Probe.bpf.c
GPL/Events/State.h
non-GPL/Events/Lib/EbpfEvents.c

Previously we were sending exit events before the file descriptors were closed. The tests are likely naive enough to always properly close the socket and then terminate. This is easy to see by connecting and killing it.
The solution is to move the hook down to ~~proc_exit_connector()~~ sched_process_exit(). In order to respect the group_dead dance we have to now keep state of who got it, we use an empty state, meaning the existence of the entry in the map is the state.

Hook exit only after descriptors are closed. Fixes #216
